const router = require('express').Router()
const serviceRouter = require('./service')
const projectRouter = require('./project')
const residentRouter = require('./resident')
const userRouter = require('./user')
const announcementRouter = require('./announcement')
const issueRouter = require('./issues') 
const reportRouter = require('./report')
const paymentRouter = require('./payment')
const dashboardRouter = require('./dashboard')
const { downloadRouter } = require('./controller')


router.use('/service', serviceRouter)
router.use('/project', projectRouter)
router.use('/resident', residentRouter)
router.use('/user', userRouter)
router.use('/announcement', announcementRouter)
router.use('/issue', issueRouter)
router.use('/report', reportRouter)
router.use('/payment', paymentRouter)
router.use('/dashboard', dashboardRouter)
router.get('/download/:filename', downloadRouter)

module.exports = router