module.exports = {
  BUILDING_DATABASE: 'servv_residence',
  SERVV_USER_TYPE_STRING: {
    ADMIN: 'admin',
    AGENT: 'agent',
    CUSTOMER: 'customer',
  },
  SERVV_USER_TYPE_NUM: {
    ADMIN: 0,
    AGENT: 1,
    CUSTOMER: 2,
  },
  ACCESS_TOKEN_EXPIRY: '3h',
  REFRESH_TOKEN_EXPIRY: '7d',

  SERVICE_INTERVAL: {
    EXPIRE_ANNOUNCEMENT: '86400000', //24 hr
  },

  ISSUE_STATUS: {
    OPEN: 0,
    INPROGRESS: 1,
    CLOSED: 2,
    ONHOLD: 3,
  },
  ISSUE_STATUS_STRING: {
    OPEN: 'OPEN',
    INPROGRESS: 'INPROGRESS',
    CLOSED: 'CLOSED',
    ONHOLD: 'ONHOLD',
  },
  ISSUE_SUB_STATUS_STRING: {
    OPEN: 'OPEN',
    SITE_VISIT_ASSIGNED: 'SITE VISIT ASSIGNED',
    SITE_VISIT_COMPLETED: 'SITE VISIT COMPLETED',
    SITE_VISIT_CANCELLED: 'SITE VISIT CANCELLED',
    ESTIMATE_DRAFT: 'ESTIMATE DRAFT',
    ESTIMATE_SENT: 'ESTIMATE SENT',
    ESTIMATE_APPROVED: 'ESTIMATE APPROVED',
    ESTIMATE_REJECTED: 'ESTIMATE REJECTED',
    WORK_ASSIGNED: 'WORK ASSIGNED',
    WORK_COMPLETED: 'WORK COMPLETED',
    WORK_CANCELLED: 'WORK CANCELLED',
    INVOICE_DRAFTED: 'INVOICE DRAFT',
    INVOICE_SENT: 'INVOICE SENT',
    PAID: 'PAID',
    CLOSED: 'CLOSED',
    ONHOLD: 'ON HOLD',
  },
  ISSUE_SUB_STATUS_NUM: {
    OPEN: 0,
    SITE_VISIT_ASSIGNED: 1,
    SITE_VISIT_COMPLETED: 2,
    SITE_VISIT_CANCELLED: 3,
    ESTIMATE_DRAFT: 4,
    ESTIMATE_SENT: 5,
    ESTIMATE_APPROVED: 6,
    ESTIMATE_REJECTED: 7,
    WORK_ASSIGNED: 8,
    WORK_COMPLETED: 9,
    WORK_CANCELLED: 10,
    INVOICE_DRAFTED: 11,
    INVOICE_APPROVED: 12,
    INVOICE_SENT: 13,
    PAID: 14,
    ONHOLD: 15,
    CLOSED: 16,
  },

  ANNOUNCEMENT_STATUS: {
    ACTIVE: 1,
    INACTIVE: 0,
    EXPIRED: 2,
  },
  QUOTATION_STATUS: {
    DRAFTED: 0,
    APPROVED: 1,
    REJECTED: 2,
    CANCELLED: 3,
    SEND: 4,
    PAID: 5
  },

  AGENT_ASSIGNMENT_STATUS: {
    PENDING: 0,
    COMPLETED: 1,
    CANCELLED: 2,
  },
  AGENT_ASSIGNMENT_TYPE: {
    SITE_VISIT: 0,
    WORK_ORDER: 1
  },

  PAYMENT_MODE: {
    CASH: 0,
    GPAY: 1,
    BANK_TRANSFER: 2
  },

  SOCKET_EVENT_CONNECT: 'connect',
  SOCKET_EVENT_DISCONNECT: 'disconnect',

  PUSH_NOTIFICATION_MESSAGE: {
    INVOICE_ISSUED_MESSAGE: "Invoice generated successfully",
  },

  REPORT_LIST: {
    ISSUE_REPORT: {
      NAME: "ISSUE REPORT",
      VALUE: 0
    },
  },
  REPORT_STATUS: {
    PENDING: 0,
    INPROGRESS: 1,
    COMPLETED: 2,
    SKIPPED: 3,
    FAILED: 4,
  },

  REPORTING_SERVICE_INTERVAL: 10000,

  SUBSCRIPTION_STATUS: {
    PENDING: 0,
    ACTIVE: 1,
    CLOSED: 2,
    COMPLETED: 3,
  },
  SUBSCRIPTION_STATUS_STRING: {
    PENDING: 'PENDING',
    ACTIVE: 'ACTIVE',
    CLOSED: 'CLOSED',
    COMPLETED: 'COMPLETED',
  },
  SUBSCRIPTION_LOG_STATUS: {
    PENDING: 0,
    COMPLETED: 1,
    FAILED: 2,
  },
  SUBSCRIPTION_LOG_STATUS_STRING: {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
  },
  SUBSCRIPTION_WEBHOOK_EVENT: {
    CHARGED: 'subscription.charged',
  },
  ORDER_WEBHOOK_EVENT: {
    CHARGED: 'payment.captured',
  },
  ORDER_TYPE: {
    ESTIMATE: 1,
    INVOICE: 2
  },
  ORDER_STATUS: {
    PENDING: 0,
    COMPLETED: 1,
    CANCELLED: 2
  },
  PAYMENT_METHOD: {
    COD: 1,
    ONLINE: 2
  },
  PAYMENT_STATUS: {
    PENDING: 0,
    COMPLETED: 1,
    FAILED: 2
  },

  TIMEZONE: "Asia/Kolkata",
  TIMEZONE_OFFSET: '+05:30',

  SATISFACTION_STATUS: {
    PENDING: 0,
    UNSATISFIED: 1,
    SATISFIED: 2
  },

  REVIEW_STATUS: {
    COMPLETED: 1,
    PENDING: 0
  },

  ANNOUNCEMENT_INTEREST: {
    INTERESTED: 1,
    NOT_INTRESTED: 0
  },

  FEES : {
    RAZORPAY: {
        PERCENTAGE: 2,
        GST_PERCENTAGE: 18,
    },
    COMPANY: {
        PERCENTAGE: 1,
        GST_PERCENTAGE: 18
    }
}
};
