module.exports = {
  BUILDING_DATABASE: 'servv_residence',
  SERVV_USER_TYPE_STRING: {
    ADMIN: 'admin',
    AGENT: 'agent',
    CUSTOMER: 'customer',
  },
  SERVV_USER_TYPE_NUM: {
    ADMIN: 0,
    AGENT: 1,
    CUSTOMER: 2,
  },
  ACCESS_TOKEN_EXPIRY: '3h',
  REFRESH_TOKEN_EXPIRY: '7d',

  SERVICE_INTERVAL: {
    EXPIRE_ANNOUNCEMENT: '86400000', //24 hr
  },

  ISSUE_STATUS: {
    OPEN: 0,
    INPROGRESS: 1,
    CLOSED: 2,
    ONHOLD: 3,
  },
  ISSUE_STATUS_STRING: {
    OPEN: 'OPEN',
    INPROGRESS: 'INPROGRESS',
    CLOSED: 'CLOSED',
    ONHOLD: 'ONHOLD',
  },
  ISSUE_SUB_STATUS_STRING: {
    OPEN: 'OPEN',
    SITE_VISIT_ASSIGNED: 'SITE VISIT ASSIGNED',
    SITE_VISIT_COMPLETED: 'SITE VISIT COMPLETED',
    SITE_VISIT_CANCELLED: 'SITE VISIT CANCELLED',
    ESTIMATE_DRAFT: 'ESTIMATE DRAFT',
    ESTIMATE_SENT: 'ESTIMATE SENT',
    ESTIMATE_APPROVED: 'ESTIMATE APPROVED',
    ESTIMATE_REJECTED: 'ESTIMATE REJECTED',
    WORK_ASSIGNED: 'WORK ASSIGNED',
    WORK_COMPLETED: 'WORK COMPLETED',
    WORK_ORDER_CANCELLED: 'WORK ORDER CANCELLED',
    INVOICE_DRAFTED: 'INVOICE DRAFTED',
    INVOICE_APPROVED: 'INVOICE APPROVED',
    INVOICE_SENT: 'INVOICE SENT',
    PAID: 'PAID',
    CLOSED: 'CLOSED',
    ONHOLD: 'ON HOLD',
  },
  ISSUE_SUB_STATUS_NUM: {
    OPEN: 0,
    SITE_VISIT_ASSIGNED: 1,
    SITE_VISIT_COMPLETED: 2,
    SITE_VISIT_CANCELLED: 3,
    ESTIMATE_DRAFT: 4,
    ESTIMATE_SENT: 5,
    ESTIMATE_APPROVED: 6,
    ESTIMATE_REJECTED: 7,
    WORK_ASSIGNED: 8,
    WORK_COMPLETED: 9,
    WORK_ORDER_CANCELLED: 10,
    INVOICE_DRAFTED: 11,
    INVOICE_APPROVED: 12,
    INVOICE_SENT: 13,
    PAID: 14,
    ONHOLD: 15,
    CLOSED: 16,
  },

  ANNOUNCEMENT_STATUS: {
    ACTIVE: 1,
    INACTIVE: 0,
    EXPIRED: 2,
  },
  QUOTATION_STATUS: {
    DRAFTED: 0,
    APPROVED: 1,
    REJECTED: 2,
    CANCELLED: 3,
    SEND: 4,
  },

  AGENT_ASSIGNMENT_STATUS: {
    PENDING: 0,
    COMPLETED: 1,
    CANCELLED: 2,
  },
  AGENT_ASSIGNMENT_TYPE: {
    SITE_VISIT: 0,
    WORK_ORDER: 1
  },

  SOCKET_EVENT_CONNECT: 'connect',
  SOCKET_EVENT_DISCONNECT: 'disconnect',
};
